name: Download CCDAY Report

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをクローン
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 必要なパッケージをインストール
        run: pip install selenium webdriver-manager

      - name: cookies.pkl を復元
        run: |
          echo "${{ secrets.CCDAY_COOKIES_B64 }}" | base64 -d > cookies.pkl

      - name: ダウンロードスクリプトを実行
        env:
          CCDAY_EMAIL: ${{ secrets.CCDAY_EMAIL }}
          CCDAY_PASSWORD: ${{ secrets.CCDAY_PASSWORD }}
        run: python download_ccday.py
